# Generated by Django 5.1.1 on 2024-09-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polls',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='polls',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
