# Generated by Django 5.1.1 on 2024-09-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_polls_email_polls_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
