# Generated by Django 5.1.1 on 2024-11-17 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_rename_choices_choice_choice_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='que',
            new_name='question',
        ),
    ]
